### ISSUE TITLE
Does Not Work with Dolphin emulator.

### ISSUE THREAD

**Issue by aRandomShyGuy** [skawo/Super-Paper-Mario-Level-Editor-Randomizer#10]
When I attempted to extract the ISO it gave this message. Please help.

"Unhandled exception has occurred in your application. If you click Continue, the application will ignore this error and attempt to continue. If you click Quit the application will close immediately. 
Illegal characters in path." 

Details "CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll ---------------------------------------- System.Xml Assembly Version: 4.0.0.0 Win32 Version: 4.8.4161.0 built by: NET48REL1 CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll ---------------------------------------- Accessibility Assembly Version: 4.0.0.0 Win32 Version: 4.8.4161.0 built by: NET48REL1 CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll ---------------------------------------- Newtonsoft.Json Assembly Version: 12.0.0.0 Win32 Version: 12.0.3.23909 CodeBase: file:///C:/Games/Randomizer/Newtonsoft.Json.DLL ---------------------------------------- System.Numerics Assembly Version: 4.0.0.0 Win32 Version: 4.8.4161.0 built by: NET48REL1 CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll ---------------------------------------- System.Runtime.Serialization Assembly Version: 4.0.0.0 Win32 Version: 4.8.4536.0 built by: NET48REL1LAST_C CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll ---------------------------------------- System.Data Assembly Version: 4.0.0.0 Win32 Version: 4.8.4584.0 built by: NET48REL1LAST_B CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll ---------------------------------------- ************** JIT Debugging ************** To enable just-in-time (JIT) debugging, the .config file for this application or computer (machine.config) must have the jitDebugging value set in the system.windows.forms section. The application must also be compiled with debugging enabled. For example: <configuration> <system.windows.forms jitDebugging="true" /> </configuration> When JIT debugging is enabled, any unhandled exception will be sent to the JIT debugger registered on the computer rather than be handled by this dialog box."

**Comment by skawo** [comment]
"Illegal characters in path."

Where is the ISO you're trying to extract? Please copy the entire path to it and send here; right click on the ISO file, click "Properties" and make a screenshot of that window.

**Comment by aRandomShyGuy** [comment]
path is c:\ROMS\Super Paper Mario.wbfs
![image](https://user-images.githubusercontent.com/130589165/233804031-316f24e3-c90d-45f3-b15c-f247cb91b3a2.png)

**Comment by skawo** [comment]
Did you extract the whole randomizer archive, or are you just running it directly from something like Winrar?

**Comment by aRandomShyGuy** [comment]
I extract the whole randomizer.

**Comment by skawo** [comment]
And where are you telling it to extract the ROM?

**Comment by aRandomShyGuy** [comment]
C:\games\.  Have tried multiple paths...

**Comment by skawo** [comment]
Well, that's odd. Any idea why it wouldn't like any of the paths? I'll give this a try on Windows 11, as I've never tested it there.

For now, extract your game with Dolphin: right click it on the game list, click properties, last tab, right click the top item and select "extract entire disc".

**Comment by aRandomShyGuy** [comment]
That sort of worked!  I'm able to extract it to a folder, find the setup folder and randomize.  But I can't play in dolphin because I dont have a  "main.dol" or a DATA/sys folder.  I tried to pack the pack the iso but I get "This folder doesnt seem to contain the super mario bros files..."  Here's what my Dolphin extract looks like:
![image](https://user-images.githubusercontent.com/130589165/233804591-e8656c6e-4c3d-492a-a8f6-97e695ff83d2.png)

The ROM is tested and working before extracting.

**Comment by skawo** [comment]
I think you right clicked on the Data partition, or selected "extract files"
You need to click here:
![image](https://user-images.githubusercontent.com/43761362/233804803-83765122-b3e0-428e-a45c-b63638c4cd2a.png)

Also, make sure the folder you're extracting to is empty.

**Comment by aRandomShyGuy** [comment]
I don't see that option...
![image](https://user-images.githubusercontent.com/130589165/233805129-0b11e5e9-69ea-4d47-8142-55d9934bccfa.png)

**Comment by skawo** [comment]
Which Dolphin version are you using?

**Comment by aRandomShyGuy** [comment]
Dolphin 5.0  Do I need a newer version?

**Comment by skawo** [comment]
Yes, 5.0, while called "stable" is ancient - going on about 7 years now. Get one of the beta versions:
https://dolphin-emu.org/download/?ref=btn

**Comment by aRandomShyGuy** [comment]
Okay it's working now. Thank you. :)

**Comment by aRandomShyGuy** [comment]
You can mark this as completed now. :)
