### ISSUE TITLE
dimentio game crash

### ISSUE THREAD

**Issue by MiloCharmingMagician** [skawo/Super-Paper-Mario-Level-Editor-Randomizer#2]
normal dimentio boss seems to crash the game and go on screenlock.

**Comment by skawo** [comment]
Well, he IS marked as crashing, so...

**Comment by MiloCharmingMagician** [comment]
How can it be fixed?

**Comment by skawo** [comment]
Just turn Dimentio off in the preset.

**Comment by MiloCharmingMagician** [comment]
I mean having Dimentio Boss in the level without frezzeing the game

**Comment by skawo** [comment]
That's not currently possible.

**Comment by MiloCharmingMagician** [comment]
Why is that?

**Comment by skawo** [comment]
Because the Dimentio code itself would have to be changed, which is outside of the scope of this project.

**Comment by MiloCharmingMagician** [comment]
But why does Dimentio code crash the level? that's what I don't get

**Comment by skawo** [comment]
Hard to say. Dimentio is fought in the "Dimentio Dimension" in the original game, so perhaps the game expects a particularly sized room or something.
