### ISSUE TITLE
[Question] What exactly does it randomize?

### ISSUE THREAD

**Issue by ghost** [skawo/Super-Paper-Mario-Level-Editor-Randomizer#4]
title

**Comment by skawo** [comment]
Just enemies.

**Comment by ghost** [comment]
Only normal enemies or also bosses?
So could there be super dimentio at the start and a goomba instead of super dimentio?

**Comment by skawo** [comment]
Anything you choose in the preset, including bosses.
Mind that some bosses like to crash, though.

**Comment by ghost** [comment]
Is it theoretically possible to implement enemy health and enemy spawn randomization?
And also,would warp point randomization be possibe to implement?
And what is with item randomization?

**Comment by skawo** [comment]
Of course it's possible, but outside of the scope of this, and I myself wouldn't know how to do it.
