### ISSUE TITLE
Seed functionality

### ISSUE THREAD

**Issue by DylanGTech** [skawo/Super-Paper-Mario-Level-Editor-Randomizer#6]
I find that giving the user an optional seed value input could greatly increase the amount of fun users could have with the randomizer. It could be added as a separate value to the Preset, that is used as the input for the RNG for the Randomizer. This would prevent people from sharing ROMs illegally.

I may do a PR at some point with this change, since it's simple enough

**Comment by skawo** [comment]
There, done. I didn't add it to the preset, though, because that would make re-randomizing a bit of a hassle; it's in the main editor window instead.
Is this acceptable?

**Comment by DylanGTech** [comment]
That was fast! Good work!

I had debated the idea of putting the seed value in the preset JSON file itself as a nullable field.

The reasoning behind the seed is so one can share an exact same game without having to share a ROM, which would present a legal issue. Instead sharing a file to load in to get the same world with your own ROM. But one could argue it negates the idea of a RANDOMIZATION preset.

This would require making the seed a nullable int within the Preset class, and when saving the preset, have an option to opt-in or opt-out of saving the randomly-generated seed. Likewise when loading in the preset, if the seed was null or the field was not present, it would just put in a random seed for when you randomize.

Although it would be a lot of hassle just for making a seed save inside the file when needed. One could just share the seed as well as the randomization file of need be. Making that change is up to you of course.


Thanks for the quick work by the way!

**Comment by skawo** [comment]
Alright, did that as well.

**Comment by DylanGTech** [comment]
Perfect! Thanks for doing that. Have a good one!
