### ISSUE TITLE
Setting up the Randomizer

### ISSUE THREAD

**Issue by RandomBat** [skawo/Super-Paper-Mario-Level-Editor-Randomizer#7]
I don't think I'm doing this right. I followed the ReadMe, but for some reason I can't get the stages and enemies to pop up in the level editor. When I try to do the "Open setup folder..." and click on the files folder, no error is given but no levels appear. Is there any way to help? Also, is there any other guides out there for setting this up besides the readme?

**Comment by skawo** [comment]
"Navigate to the DATA/files folder. Select the "setup" folder there. "

You're supposed to open the "setup" folder that's found in the "files" folder, not the files folder itself.

**Comment by RandomBat** [comment]
OH. That makes sense thanks for clearing this up lmao
