### ISSUE TITLE
Game crashes if multiple enemy Bowsers try to breathe fire at the same time

### ISSUE THREAD

**Issue by fawfulthegreat** [skawo/Super-Paper-Mario-Level-Editor-Randomizer#8]
This includes both boss Bowsers and Dark Bowser, and any combination of them. Player Bowser's fire has no impact on it. It would be an easy fix (I'd assume) by just adding something that checks to make sure every room has only a max of 1 Bowser and if there's more, re-rolling them.

**Comment by skawo** [comment]
Done~
